[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "iana-protocol-numbers"
version = "0.1.0"
description = "A python library for network protocol mappings"
requires-python = ">=3.9" 